sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3

services:
    - docker

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev

script:
    - sudo pip --no-cache-dir install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pylint \
        coveralls \
        codecov
    - sudo pip --no-cache-dir install \
        aipy \
        pyephem \
        astropy
    - sudo python -c "from astropy.utils.data import download_file; download_file('ftp://ftp.iers.org/products/eop/rapid/standard/finals2000A.all', cache=True)"
    - sudo python setup.py build
    - sudo python setup.py test

after_success:
    - cd tests
    - coveralls
    - codecov

cache:
  directories:
    - $HOME/.astropy/cache
