sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3


before_install:
    - sudo apt-get update
    - sudo apt-get -y install \
         build-essential \
         curl \
         git \
         pkg-config \
         software-properties-common \
         python-dev \
         python3-dev \
         libfftw3-dev

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pyephem==3.7.6.0 \
        coveralls \
        codecov
    - pip install aipy
    - pip install .

script:
    - python setup.py test
    - coverage run --source=lsl -m unittest discover tests

after_success:    
    - coveralls
    - codecov

cache:
  directories:
    - $HOME/.astropy/cache
