sudo: required
  
language: python

python:
    - 2.7
    - 3.6
    ## PyPy versions
    #- pypy2.7-6.0
    #- pypy3


jobs:
  allow_failures:
    - os: osx
    
  include:
    - os: osx
      osx_image: xcode11
      language: sh
      env:
        - HOMEBREW_NO_INSTALL_CLEANUP=1
        - HOMEBREW_NO_ANALYTICS=1
      before_cache:
        # - brew cleanup
        # - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          # - "$HOME/Library/Caches/Homebrew"
          # - "$HOME/Library/Caches/pip"


addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libgdbm-dev
            - libfftw3-dev
            - libcfitsio-dev
            - libboost-python-dev
    homebrew:
        # update: true
        packages:
            - python3
            - pkg-config
            - git
            - fftw

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:kernsuite/kern-3; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -q update; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install casacore-dev wcslib-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pip install --upgrade virtualenv; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then virtualenv -p python3 --system-site-packages "$HOME/venv"; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source "$HOME/venv/bin/activate"; fi

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pyephem==3.7.6.0 \
        jupyterlab \
        jupyter_client \
        nbformat \
        nbconvert \
        coveralls \
        codecov
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install python-casacore; fi
    - pip install "astropy<3.2"
    - pip install aipy
    - pip install .

script:
    - cd tests
    - coverage run --source=lsl -m unittest discover

after_success:
    - cd tests
    - coveralls
    - codecov

cache:
  directories:
    - $HOME/.astropy/cache

before_cache:
    - cp -f $HOME/.astropy/cache/download/py3/* $HOME/.astropy/cache/download/py2/
    - find $HOME/.astropy | xargs ls -l
